# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := nacl_bootstrap_raw
### Rules for action "link_with_ld_bfd":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_src_trusted_service_runtime_linux_nacl_bootstrap_gyp_nacl_bootstrap_raw_target_link_with_ld_bfd = ACTION Linking nacl_bootstrap_raw $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_src_trusted_service_runtime_linux_nacl_bootstrap_gyp_nacl_bootstrap_raw_target_link_with_ld_bfd = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client/src/trusted/service_runtime/linux; mkdir -p $(builddir); python ld_bfd.py --compiler g++ -m elf_x86_64 --build-id -static --defsym "RESERVE_TOP=0x0" "--script=nacl_bootstrap.x" -o "$(builddir)/nacl_bootstrap_raw" -z "max-page-size=0x1000" --whole-archive "$(obj)/gen/nacl_bootstrap/libnacl_bootstrap_lib.a" --no-whole-archive

$(builddir)/nacl_bootstrap_raw: obj := $(abs_obj)
$(builddir)/nacl_bootstrap_raw: builddir := $(abs_builddir)
$(builddir)/nacl_bootstrap_raw: TOOLSET := $(TOOLSET)
$(builddir)/nacl_bootstrap_raw: native_client/src/trusted/service_runtime/linux/nacl_bootstrap.x $(obj)/gen/nacl_bootstrap/libnacl_bootstrap_lib.a native_client/src/trusted/service_runtime/linux/ld_bfd.py FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_src_trusted_service_runtime_linux_nacl_bootstrap_gyp_nacl_bootstrap_raw_target_link_with_ld_bfd)

all_deps += $(builddir)/nacl_bootstrap_raw
action__home_david_Projects_spa_examples_chromium_src_native_client_src_trusted_service_runtime_linux_nacl_bootstrap_gyp_nacl_bootstrap_raw_target_link_with_ld_bfd_outputs := $(builddir)/nacl_bootstrap_raw


### Rules for final target.
# Build our special outputs first.
$(obj).target/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_raw.stamp: | $(action__home_david_Projects_spa_examples_chromium_src_native_client_src_trusted_service_runtime_linux_nacl_bootstrap_gyp_nacl_bootstrap_raw_target_link_with_ld_bfd_outputs)

# Preserve order dependency of special output on deps.
$(action__home_david_Projects_spa_examples_chromium_src_native_client_src_trusted_service_runtime_linux_nacl_bootstrap_gyp_nacl_bootstrap_raw_target_link_with_ld_bfd_outputs): | $(obj)/gen/nacl_bootstrap/libnacl_bootstrap_lib.a

$(obj).target/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_raw.stamp: TOOLSET := $(TOOLSET)
$(obj).target/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_raw.stamp: $(obj)/gen/nacl_bootstrap/libnacl_bootstrap_lib.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_raw.stamp
# Add target alias
.PHONY: nacl_bootstrap_raw
nacl_bootstrap_raw: $(obj).target/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_raw.stamp

# Add target alias to "all" target.
.PHONY: all
all: nacl_bootstrap_raw

