.\" btcheck
.TH BTCHECK "6" "December 2005" "btcheck 1.05" "BitTorrent"
.SH NAME
btcheck \- Verify a the files listed in a BitTorrent torrent against those on disk
.SH SYNOPSIS
.B btcheck
[\fITORRENT\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Used to test each of the blocks of a torrent for correctness and list which
blocks are correct.

.SH AUTHOR
Written by Kevin Smathers and all of the authors listed in CREDITS
.SH "REPORTING BUGS"
Report bugs at <http://www.sf.net/projects/libbt>
.SH COPYRIGHT
Copyright \(co 2004 Kevin Smathers, et. al.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
btget(1), btlist(1)
