# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := net_unittests
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSE_KERBEROS' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wheader-hygiene \
	-Wno-unused-function \
	-Wno-char-subscripts \
	-Wno-unnamed-type-template-args \
	-Wno-c++11-extensions \
	-Wno-covered-switch-default \
	-Wstring-conversion \
	-Xclang \
	-load \
	-Xclang \
	/home/david/Projects/spa/examples/chromium/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so \
	-Xclang \
	-add-plugin \
	-Xclang \
	find-bad-constructs \
	-Xclang \
	-plugin-arg-find-bad-constructs \
	-Xclang \
	skip-virtuals-in-implementations \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/freetype2 \
	-I/usr/include/pixman-1 \
	-I/usr/include/libpng12 \
	-I/usr/include/harfbuzz \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-I/usr/include/dbus-1.0 \
	-I/usr/lib/x86_64-linux-gnu/dbus-1.0/include \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include \
	-Ithird_party/zlib \
	-Inet/third_party/nss/ssl

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSE_KERBEROS' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wheader-hygiene \
	-Wno-unused-function \
	-Wno-char-subscripts \
	-Wno-unnamed-type-template-args \
	-Wno-c++11-extensions \
	-Wno-covered-switch-default \
	-Wstring-conversion \
	-Xclang \
	-load \
	-Xclang \
	/home/david/Projects/spa/examples/chromium/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so \
	-Xclang \
	-add-plugin \
	-Xclang \
	find-bad-constructs \
	-Xclang \
	-plugin-arg-find-bad-constructs \
	-Xclang \
	skip-virtuals-in-implementations \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/freetype2 \
	-I/usr/include/pixman-1 \
	-I/usr/include/libpng12 \
	-I/usr/include/harfbuzz \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/nss \
	-I/usr/include/nspr \
	-I/usr/include/dbus-1.0 \
	-I/usr/lib/x86_64-linux-gnu/dbus-1.0/include \
	-O2 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-I. \
	-Itesting/gmock/include \
	-Itesting/gtest/include \
	-Ithird_party/zlib \
	-Inet/third_party/nss/ssl

OBJS := \
	$(obj).target/$(TARGET)/net/base/address_list_unittest.o \
	$(obj).target/$(TARGET)/net/base/address_tracker_linux_unittest.o \
	$(obj).target/$(TARGET)/net/base/backoff_entry_unittest.o \
	$(obj).target/$(TARGET)/net/base/big_endian_unittest.o \
	$(obj).target/$(TARGET)/net/base/data_url_unittest.o \
	$(obj).target/$(TARGET)/net/base/directory_lister_unittest.o \
	$(obj).target/$(TARGET)/net/base/dns_util_unittest.o \
	$(obj).target/$(TARGET)/net/base/escape_unittest.o \
	$(obj).target/$(TARGET)/net/base/expiring_cache_unittest.o \
	$(obj).target/$(TARGET)/net/base/file_stream_unittest.o \
	$(obj).target/$(TARGET)/net/base/filter_unittest.o \
	$(obj).target/$(TARGET)/net/base/int128_unittest.o \
	$(obj).target/$(TARGET)/net/base/gzip_filter_unittest.o \
	$(obj).target/$(TARGET)/net/base/host_mapping_rules_unittest.o \
	$(obj).target/$(TARGET)/net/base/host_port_pair_unittest.o \
	$(obj).target/$(TARGET)/net/base/ip_endpoint_unittest.o \
	$(obj).target/$(TARGET)/net/base/keygen_handler_unittest.o \
	$(obj).target/$(TARGET)/net/base/mime_sniffer_unittest.o \
	$(obj).target/$(TARGET)/net/base/mime_util_unittest.o \
	$(obj).target/$(TARGET)/net/base/mock_filter_context.o \
	$(obj).target/$(TARGET)/net/base/net_log_unittest.o \
	$(obj).target/$(TARGET)/net/base/net_util_unittest.o \
	$(obj).target/$(TARGET)/net/base/prioritized_dispatcher_unittest.o \
	$(obj).target/$(TARGET)/net/base/priority_queue_unittest.o \
	$(obj).target/$(TARGET)/net/base/registry_controlled_domains/registry_controlled_domain_unittest.o \
	$(obj).target/$(TARGET)/net/base/sdch_filter_unittest.o \
	$(obj).target/$(TARGET)/net/base/static_cookie_policy_unittest.o \
	$(obj).target/$(TARGET)/net/base/test_completion_callback_unittest.o \
	$(obj).target/$(TARGET)/net/base/upload_bytes_element_reader_unittest.o \
	$(obj).target/$(TARGET)/net/base/upload_data_stream_unittest.o \
	$(obj).target/$(TARGET)/net/base/upload_file_element_reader_unittest.o \
	$(obj).target/$(TARGET)/net/base/url_util_unittest.o \
	$(obj).target/$(TARGET)/net/cert/cert_verify_proc_unittest.o \
	$(obj).target/$(TARGET)/net/cert/crl_set_unittest.o \
	$(obj).target/$(TARGET)/net/cert/ev_root_ca_metadata_unittest.o \
	$(obj).target/$(TARGET)/net/cert/multi_threaded_cert_verifier_unittest.o \
	$(obj).target/$(TARGET)/net/cert/nss_cert_database_unittest.o \
	$(obj).target/$(TARGET)/net/cert/pem_tokenizer_unittest.o \
	$(obj).target/$(TARGET)/net/cert/x509_certificate_unittest.o \
	$(obj).target/$(TARGET)/net/cert/x509_util_unittest.o \
	$(obj).target/$(TARGET)/net/cert/x509_util_nss_unittest.o \
	$(obj).target/$(TARGET)/net/cookies/canonical_cookie_unittest.o \
	$(obj).target/$(TARGET)/net/cookies/cookie_constants_unittest.o \
	$(obj).target/$(TARGET)/net/cookies/cookie_monster_unittest.o \
	$(obj).target/$(TARGET)/net/cookies/cookie_util_unittest.o \
	$(obj).target/$(TARGET)/net/cookies/parsed_cookie_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/addr_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/backend_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/bitmap_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/block_files_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/cache_util_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/entry_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/mapped_file_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/simple/simple_index_file_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/simple/simple_index_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/simple/simple_util_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/storage_block_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/flash/log_store_entry_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/flash/log_store_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/flash/segment_unittest.o \
	$(obj).target/$(TARGET)/net/disk_cache/flash/storage_unittest.o \
	$(obj).target/$(TARGET)/net/dns/address_sorter_posix_unittest.o \
	$(obj).target/$(TARGET)/net/dns/address_sorter_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_config_service_posix_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_config_service_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_hosts_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_query_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_response_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_session_unittest.o \
	$(obj).target/$(TARGET)/net/dns/dns_transaction_unittest.o \
	$(obj).target/$(TARGET)/net/dns/host_cache_unittest.o \
	$(obj).target/$(TARGET)/net/dns/host_resolver_impl_unittest.o \
	$(obj).target/$(TARGET)/net/dns/mapped_host_resolver_unittest.o \
	$(obj).target/$(TARGET)/net/dns/serial_worker_unittest.o \
	$(obj).target/$(TARGET)/net/dns/single_request_host_resolver_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_auth_cache_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_ctrl_response_buffer_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_directory_listing_parser_ls_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_directory_listing_parser_netware_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_directory_listing_parser_os2_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_directory_listing_parser_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_directory_listing_parser_vms_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_directory_listing_parser_windows_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_network_transaction_unittest.o \
	$(obj).target/$(TARGET)/net/ftp/ftp_util_unittest.o \
	$(obj).target/$(TARGET)/net/http/des_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_cache_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_controller_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_filter_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_gssapi_posix_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_handler_basic_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_handler_digest_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_handler_factory_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_handler_mock.o \
	$(obj).target/$(TARGET)/net/http/http_auth_handler_negotiate_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_handler_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_auth_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_byte_range_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_cache_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_chunked_decoder_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_content_disposition_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_network_layer_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_network_transaction_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_network_transaction_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_network_transaction_ssl_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_pipelined_connection_impl_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_pipelined_host_forced_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_pipelined_host_impl_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_pipelined_host_pool_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_pipelined_host_test_util.o \
	$(obj).target/$(TARGET)/net/http/http_pipelined_network_transaction_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_proxy_client_socket_pool_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_proxy_client_socket_pool_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_request_headers_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_response_body_drainer_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_response_headers_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_security_headers_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_server_properties_impl_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_stream_factory_impl_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_stream_parser_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_transaction_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_util_unittest.o \
	$(obj).target/$(TARGET)/net/http/http_vary_data_unittest.o \
	$(obj).target/$(TARGET)/net/http/mock_allow_url_security_manager.o \
	$(obj).target/$(TARGET)/net/http/mock_gssapi_library_posix.o \
	$(obj).target/$(TARGET)/net/http/mock_http_cache.o \
	$(obj).target/$(TARGET)/net/http/transport_security_state_unittest.o \
	$(obj).target/$(TARGET)/net/http/url_security_manager_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/dhcp_proxy_script_fetcher_factory_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/multi_threaded_proxy_resolver_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/network_delegate_error_observer_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_bypass_rules_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_config_service_linux_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_config_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_info_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_list_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_resolver_v8_tracing_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_resolver_v8_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_script_decider_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_script_fetcher_impl_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_server_unittest.o \
	$(obj).target/$(TARGET)/net/proxy/proxy_service_unittest.o \
	$(obj).target/$(TARGET)/net/quic/blocked_list_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/available_channel_estimator_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/channel_estimator_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/cube_root_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/cubic_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/fix_rate_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/hybrid_slow_start_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/inter_arrival_bitrate_ramp_up_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/inter_arrival_overuse_detector_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/inter_arrival_probe_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/inter_arrival_receiver_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/inter_arrival_state_machine_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/inter_arrival_sender_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/leaky_bucket_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/paced_sender_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/quic_congestion_control_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/quic_congestion_manager_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/quic_max_sized_map_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/tcp_cubic_sender_test.o \
	$(obj).target/$(TARGET)/net/quic/congestion_control/tcp_receiver_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/aes_128_gcm_decrypter_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/aes_128_gcm_encrypter_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/crypto_framer_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/crypto_handshake_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/curve25519_key_exchange_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/null_decrypter_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/null_encrypter_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/p256_key_exchange_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/quic_random_test.o \
	$(obj).target/$(TARGET)/net/quic/crypto/strike_register_test.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/crypto_test_utils.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/mock_clock.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/mock_crypto_client_stream.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/mock_crypto_client_stream_factory.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/mock_random.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/quic_connection_peer.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/quic_framer_peer.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/quic_packet_creator_peer.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/quic_session_peer.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/quic_test_utils.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/reliable_quic_stream_peer.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/simple_quic_framer.o \
	$(obj).target/$(TARGET)/net/quic/test_tools/test_task_runner.o \
	$(obj).target/$(TARGET)/net/quic/quic_bandwidth_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_client_session_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_clock_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_connection_helper_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_connection_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_crypto_client_stream_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_crypto_server_stream_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_crypto_stream_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_data_writer_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_fec_group_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_framer_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_http_stream_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_network_transaction_unittest.o \
	$(obj).target/$(TARGET)/net/quic/quic_packet_creator_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_packet_entropy_manager_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_packet_generator_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_protocol_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_reliable_client_stream_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_session_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_stream_factory_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_stream_sequencer_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_time_test.o \
	$(obj).target/$(TARGET)/net/quic/quic_utils_test.o \
	$(obj).target/$(TARGET)/net/quic/reliable_quic_stream_test.o \
	$(obj).target/$(TARGET)/net/socket/buffered_write_stream_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/client_socket_pool_base_unittest.o \
	$(obj).target/$(TARGET)/net/socket/deterministic_socket_data_unittest.o \
	$(obj).target/$(TARGET)/net/socket/mock_client_socket_pool_manager.o \
	$(obj).target/$(TARGET)/net/socket/socks5_client_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/socks_client_socket_pool_unittest.o \
	$(obj).target/$(TARGET)/net/socket/socks_client_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/ssl_client_socket_pool_unittest.o \
	$(obj).target/$(TARGET)/net/socket/ssl_client_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/ssl_server_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/tcp_client_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/tcp_listen_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/tcp_server_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/transport_client_socket_pool_unittest.o \
	$(obj).target/$(TARGET)/net/socket/transport_client_socket_unittest.o \
	$(obj).target/$(TARGET)/net/socket/unix_domain_socket_posix_unittest.o \
	$(obj).target/$(TARGET)/net/socket_stream/socket_stream_metrics_unittest.o \
	$(obj).target/$(TARGET)/net/socket_stream/socket_stream_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/buffered_spdy_framer_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/buffered_spdy_framer_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_credential_builder_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_buffer_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_credential_state_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_frame_builder_test.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_frame_reader_test.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_framer_test.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_header_block_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_http_stream_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_http_stream_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_http_utils_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_network_transaction_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_network_transaction_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_priority_forest_test.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_protocol_test.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_proxy_client_socket_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_proxy_client_socket_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_read_queue_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_session_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_session_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_session_test_util.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_stream_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_stream_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_stream_test_util.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_test_util_common.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_test_util_spdy3.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_test_util_spdy2.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_test_utils.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_websocket_stream_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_websocket_stream_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_websocket_test_util_spdy2.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_websocket_test_util_spdy3.o \
	$(obj).target/$(TARGET)/net/spdy/spdy_write_queue_unittest.o \
	$(obj).target/$(TARGET)/net/ssl/client_cert_store_impl_unittest.o \
	$(obj).target/$(TARGET)/net/ssl/default_server_bound_cert_store_unittest.o \
	$(obj).target/$(TARGET)/net/ssl/server_bound_cert_service_unittest.o \
	$(obj).target/$(TARGET)/net/ssl/ssl_cipher_suite_names_unittest.o \
	$(obj).target/$(TARGET)/net/ssl/ssl_client_auth_cache_unittest.o \
	$(obj).target/$(TARGET)/net/ssl/ssl_config_service_unittest.o \
	$(obj).target/$(TARGET)/net/test/python_utils_unittest.o \
	$(obj).target/$(TARGET)/net/test/run_all_unittests.o \
	$(obj).target/$(TARGET)/net/tools/dump_cache/url_to_filename_encoder.o \
	$(obj).target/$(TARGET)/net/tools/dump_cache/url_to_filename_encoder_unittest.o \
	$(obj).target/$(TARGET)/net/tools/dump_cache/url_utilities.o \
	$(obj).target/$(TARGET)/net/tools/dump_cache/url_utilities_unittest.o \
	$(obj).target/$(TARGET)/net/udp/udp_socket_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_fetcher_impl_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_context_builder_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_filter_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_ftp_job_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_http_job_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_job_factory_impl_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_job_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_throttler_simulation_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_throttler_test_support.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_throttler_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/url_request_unittest.o \
	$(obj).target/$(TARGET)/net/url_request/view_cache_helper_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_errors_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_frame_parser_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_frame_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_handshake_handler_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_handshake_handler_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_handshake_handler_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_job_spdy2_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_job_spdy3_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_net_log_params_unittest.o \
	$(obj).target/$(TARGET)/net/websockets/websocket_throttle_unittest.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/base/libbase.a $(obj).target/base/libbase_i18n.a $(obj).target/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/crypto/libcrcrypto.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/net/libnet.a $(obj).target/net/libnet_test_support.a $(obj).target/build/linux/ssl.stamp $(obj).target/build/linux/gtk.stamp $(obj).target/base/allocator/liballocator.a $(obj).target/net/libnet_with_v8.a $(obj).target/build/linux/dbus.stamp $(obj).target/dbus/libdbus_test_support.a $(obj).target/base/libbase_static.a $(obj).target/base/allocator/liballocator_extension_thunks.a $(obj).target/testing/gtest_prod.stamp $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/base/libsymbolize.a $(obj).target/build/linux/glib.stamp $(obj).target/base/libxdg_mime.a $(obj).target/build/linux/x11.stamp $(obj).target/third_party/libevent/libevent.a $(obj).target/third_party/icu/libicui18n.a $(obj).target/third_party/icu/libicuuc.a $(obj).target/third_party/icu/libicudata.a $(obj).target/net/third_party/nss/libcrssl.a $(obj).target/sdch/libsdch.a $(obj).target/net/net_resources.stamp $(obj).target/build/linux/gconf.stamp $(obj).target/build/linux/libgio.a $(obj).target/build/linux/libresolv.stamp $(obj).target/build/linux/gdk.stamp $(obj).target/dbus/libdbus.a $(obj).target/third_party/protobuf/libprotobuf_lite.a $(obj).target/base/libtest_support_base.a $(obj).target/third_party/protobuf/py_proto.stamp $(obj).target/v8/tools/gyp/v8.stamp $(obj).target/v8/tools/gyp/libv8_base.x64.a $(obj).target/v8/tools/gyp/libv8_snapshot.a $(obj).host/v8/tools/gyp/js2c.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-Wl,-uIsHeapProfilerRunning,-uProfilerStart \
	-Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi \
	-Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl \
	-Wl,-u_ZN15HeapLeakChecker12IgnoreObjectEPKv,-u_ZN15HeapLeakChecker14UnIgnoreObjectEPKv \
	-Wl,--icf=none

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-Wl,-uIsHeapProfilerRunning,-uProfilerStart \
	-Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi \
	-Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl \
	-Wl,-u_ZN15HeapLeakChecker12IgnoreObjectEPKv,-u_ZN15HeapLeakChecker14UnIgnoreObjectEPKv \
	-Wl,--icf=none \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	-lrt \
	-ldl \
	-lgmodule-2.0 \
	-lgobject-2.0 \
	-lgthread-2.0 \
	-lglib-2.0 \
	-lXtst \
	-lgtk-x11-2.0 \
	-lgdk-x11-2.0 \
	-latk-1.0 \
	-lgio-2.0 \
	-lpangoft2-1.0 \
	-lpangocairo-1.0 \
	-lgdk_pixbuf-2.0 \
	-lcairo \
	-lpango-1.0 \
	-lfontconfig \
	-lfreetype \
	-lX11 \
	-lXi \
	-lnss3 \
	-lnssutil3 \
	-lsmime3 \
	-lplds4 \
	-lplc4 \
	-lnspr4 \
	-lgconf-2 \
	-lresolv \
	-ldbus-1

$(builddir)/net_unittests: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/net_unittests: LIBS := $(LIBS)
$(builddir)/net_unittests: LD_INPUTS := $(OBJS) $(obj).target/base/libbase.a $(obj).target/base/libbase_i18n.a $(obj).target/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/crypto/libcrcrypto.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/net/libnet.a $(obj).target/net/libnet_test_support.a $(obj).target/base/allocator/liballocator.a $(obj).target/net/libnet_with_v8.a $(obj).target/dbus/libdbus_test_support.a $(obj).target/base/libbase_static.a $(obj).target/base/allocator/liballocator_extension_thunks.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/base/libsymbolize.a $(obj).target/base/libxdg_mime.a $(obj).target/third_party/libevent/libevent.a $(obj).target/third_party/icu/libicui18n.a $(obj).target/third_party/icu/libicuuc.a $(obj).target/third_party/icu/libicudata.a $(obj).target/net/third_party/nss/libcrssl.a $(obj).target/sdch/libsdch.a $(obj).target/build/linux/libgio.a $(obj).target/dbus/libdbus.a $(obj).target/third_party/protobuf/libprotobuf_lite.a $(obj).target/base/libtest_support_base.a $(obj).target/v8/tools/gyp/libv8_base.x64.a $(obj).target/v8/tools/gyp/libv8_snapshot.a
$(builddir)/net_unittests: TOOLSET := $(TOOLSET)
$(builddir)/net_unittests: $(OBJS) $(obj).target/base/libbase.a $(obj).target/base/libbase_i18n.a $(obj).target/base/third_party/dynamic_annotations/libdynamic_annotations.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/crypto/libcrcrypto.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/net/libnet.a $(obj).target/net/libnet_test_support.a $(obj).target/base/allocator/liballocator.a $(obj).target/net/libnet_with_v8.a $(obj).target/dbus/libdbus_test_support.a $(obj).target/base/libbase_static.a $(obj).target/base/allocator/liballocator_extension_thunks.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/base/libsymbolize.a $(obj).target/base/libxdg_mime.a $(obj).target/third_party/libevent/libevent.a $(obj).target/third_party/icu/libicui18n.a $(obj).target/third_party/icu/libicuuc.a $(obj).target/third_party/icu/libicudata.a $(obj).target/net/third_party/nss/libcrssl.a $(obj).target/sdch/libsdch.a $(obj).target/build/linux/libgio.a $(obj).target/dbus/libdbus.a $(obj).target/third_party/protobuf/libprotobuf_lite.a $(obj).target/base/libtest_support_base.a $(obj).target/v8/tools/gyp/libv8_base.x64.a $(obj).target/v8/tools/gyp/libv8_snapshot.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/net_unittests
# Add target alias
.PHONY: net_unittests
net_unittests: $(builddir)/net_unittests

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/net_unittests

