# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := net_unittests_run
### Rules for action "isolate":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate = ACTION _home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate $@
cmd__home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd net; mkdir -p $(builddir); python ../tools/swarm_client/isolate.py check --outdir "" --variable PRODUCT_DIR "$(builddir)" --variable OS linux --result "$(builddir)/net_unittests.isolated" --isolate net_unittests.isolate

$(builddir)/net_unittests.isolated: obj := $(abs_obj)
$(builddir)/net_unittests.isolated: builddir := $(abs_builddir)
$(builddir)/net_unittests.isolated: TOOLSET := $(TOOLSET)
$(builddir)/net_unittests.isolated: net/net_unittests.isolate testing/xvfb.py $(builddir)/xdisplaycheck chrome/test/data/animate1.gif chrome/test/data/server-unavailable.html chrome/test/data/server-unavailable.html.mock-http-headers chrome/test/data/simple.html testing/test_env.py tools/swarm_client/run_isolated.py tools/swarm_client/run_test_cases.py $(builddir)/net_unittests FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate)

all_deps += $(builddir)/net_unittests.isolated
action__home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate_outputs := $(builddir)/net_unittests.isolated


### Rules for final target.
# Build our special outputs first.
$(obj).target/net/net_unittests_run.stamp: | $(action__home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate_outputs)

# Preserve order dependency of special output on deps.
$(action__home_david_Projects_spa_examples_chromium_src_net_net_gyp_net_unittests_run_target_isolate_outputs): | $(builddir)/net_unittests

$(obj).target/net/net_unittests_run.stamp: TOOLSET := $(TOOLSET)
$(obj).target/net/net_unittests_run.stamp: $(builddir)/net_unittests FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/net/net_unittests_run.stamp
# Add target alias
.PHONY: net_unittests_run
net_unittests_run: $(obj).target/net/net_unittests_run.stamp

# Add target alias to "all" target.
.PHONY: all
all: net_unittests_run

