#!/bin/sh

CC='clang' CFLAGS="-DENABLE_SPA -DENABLE_KLEE -DSPA_FIXES -I`pwd`/../libosip2-3.6.0/include -I`pwd`/../../../include -emit-llvm -use-gold-plugin -O0 -g" \
LD='llvm-link' CPP='clang -E' AR='echo' RANLIB='echo' ./configure \
--disable-shared \
--enable-static \
--disable-tools \
--enable-debug \
--disable-trace \
--disable-mpatrol \
--disable-gprof \
--disable-mt \
--disable-openssl \
--disable-srvrec
