#!/bin/sh

CFLAGS="-DENABLE_SPA -DSPA_FIXES -I`pwd`/../libosip2-3.6.0/include -I`pwd`/../../../include -O0 -g" \
AR='echo' RANLIB='echo' ./configure \
--disable-shared \
--enable-static \
--disable-tools \
--enable-debug \
--disable-trace \
--disable-mpatrol \
--disable-gprof \
--disable-mt \
--disable-openssl \
--disable-srvrec
