# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sandbox
### Rules for final target.
$(obj).target/sandbox/sandbox.stamp: TOOLSET := $(TOOLSET)
$(obj).target/sandbox/sandbox.stamp: $(obj).target/sandbox/libsandbox_services.a $(obj).target/sandbox/libsuid_sandbox_client.a $(obj).target/sandbox/libseccomp_bpf.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/sandbox/sandbox.stamp
# Add target alias
.PHONY: sandbox
sandbox: $(obj).target/sandbox/sandbox.stamp

# Add target alias to "all" target.
.PHONY: all
all: sandbox

