# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := theme_resources
### Rules for final target.
$(obj).target/chrome/theme_resources.stamp: TOOLSET := $(TOOLSET)
$(obj).target/chrome/theme_resources.stamp: $(obj).target/chrome/chrome_unscaled_resources.stamp $(obj).target/chrome/theme_resources_gen.stamp $(obj).target/ui/ui_resources.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/chrome/theme_resources.stamp
# Add target alias
.PHONY: theme_resources
theme_resources: $(obj).target/chrome/theme_resources.stamp

# Add target alias to "all" target.
.PHONY: all
all: theme_resources

