#!/bin/sh

CC='llvm-gcc' CFLAGS='-DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g' CXX='llvm-g++' CXXFLAGS='-DENABLE_SPA -emit-llvm -use-gold-plugin -O0 -g' CPP='llvm-cpp' LD='llvm-ld' AR='echo' RANLIB='echo' ./configure \
--disable-shared \
--enable-static \
--enable-debug \
--disable-trace \
--disable-mpatrol \
--disable-gprof \
--disable-mt \
--enable-test
