# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := prep_nacl_sdk
### Rules for action "Prep x86 newlib toolchain":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain = ACTION _home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client; mkdir -p $(obj)/gen/sdk/toolchain/linux_x86_newlib; python ../native_client/build/prep_nacl_sdk.py --tool x86_newlib --path "$(obj)/gen/sdk/toolchain/linux_x86_newlib"

$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep: obj := $(abs_obj)
$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep: builddir := $(abs_builddir)
$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep: TOOLSET := $(TOOLSET)
$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep: $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h native_client/src/untrusted/nacl/nacl_dyncode.h native_client/src/untrusted/nacl/nacl_startup.h native_client/src/untrusted/nacl/nacl_thread.h native_client/src/untrusted/pthread/pthread.h native_client/src/untrusted/pthread/semaphore.h native_client/src/untrusted/stubs/crt1.x native_client/src/untrusted/valgrind/dynamic_annotations.h FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain)

all_deps += $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep
action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain_outputs := $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.prep

### Rules for action "Prep x86 glibc toolchain":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain = ACTION _home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client; mkdir -p $(obj)/gen/sdk/toolchain/linux_x86_glibc; python ../native_client/build/prep_nacl_sdk.py --tool x86_glibc --path "$(obj)/gen/sdk/toolchain/linux_x86_glibc"

$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep: obj := $(abs_obj)
$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep: builddir := $(abs_builddir)
$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep: TOOLSET := $(TOOLSET)
$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep: $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h native_client/src/untrusted/nacl/nacl_dyncode.h native_client/src/untrusted/nacl/nacl_startup.h native_client/src/untrusted/nacl/nacl_thread.h native_client/src/untrusted/valgrind/dynamic_annotations.h FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain)

all_deps += $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep
action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain_outputs := $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.prep

### Rules for action "Prep pnacl toolchain":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain = ACTION _home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client; mkdir -p $(obj)/gen/sdk/toolchain/linux_x86_pnacl; python ../native_client/build/prep_nacl_sdk.py --tool x86_pnacl --path "$(obj)/gen/sdk/toolchain/linux_x86_pnacl"

$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.prep: obj := $(abs_obj)
$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.prep: builddir := $(abs_builddir)
$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.prep: TOOLSET := $(TOOLSET)
$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.prep: $(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar native_client/src/untrusted/irt/irt.h native_client/src/untrusted/irt/irt_ppapi.h native_client/src/untrusted/nacl/nacl_dyncode.h native_client/src/untrusted/nacl/nacl_startup.h native_client/src/untrusted/nacl/nacl_thread.h native_client/src/untrusted/pthread/pthread.h native_client/src/untrusted/pthread/semaphore.h native_client/src/untrusted/valgrind/dynamic_annotations.h FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain)

all_deps += $(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.prep
action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain_outputs := $(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.prep


### Rules for final target.
# Build our special outputs first.
$(obj).target/native_client/prep_nacl_sdk.stamp: | $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain_outputs)

# Preserve order dependency of special output on deps.
$(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_newlib_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_x86_glibc_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_prep_nacl_sdk_target_Prep_pnacl_toolchain_outputs): | $(obj).target/native_client/untar_toolchains.stamp

$(obj).target/native_client/prep_nacl_sdk.stamp: TOOLSET := $(TOOLSET)
$(obj).target/native_client/prep_nacl_sdk.stamp: $(obj).target/native_client/untar_toolchains.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/native_client/prep_nacl_sdk.stamp
# Add target alias
.PHONY: prep_nacl_sdk
prep_nacl_sdk: $(obj).target/native_client/prep_nacl_sdk.stamp

# Add target alias to "all" target.
.PHONY: all
all: prep_nacl_sdk

