# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := untar_toolchains
### Rules for action "Untar x86 newlib toolchain":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain = ACTION _home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client; mkdir -p $(obj)/gen/sdk/toolchain/linux_x86_newlib; python ../native_client/build/untar_toolchain.py --tool x86_newlib --tmp "$(obj)/gen/untar" --sdk "$(obj)/gen/sdk" --os linux ../native_client/toolchain/.tars/naclsdk_linux_x86.tgz

$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar: obj := $(abs_obj)
$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar: builddir := $(abs_builddir)
$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar: TOOLSET := $(TOOLSET)
$(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar: native_client/build/cygtar.py native_client/toolchain/.tars/naclsdk_linux_x86.tgz FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain)

all_deps += $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar
action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain_outputs := $(obj)/gen/sdk/toolchain/linux_x86_newlib/stamp.untar

### Rules for action "Untar x86 glibc toolchain":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain = ACTION _home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client; mkdir -p $(obj)/gen/sdk/toolchain/linux_x86_glibc; python ../native_client/build/untar_toolchain.py --tool x86_glibc --tmp "$(obj)/gen/untar" --sdk "$(obj)/gen/sdk" --os linux ../native_client/toolchain/.tars/toolchain_linux_x86.tar.bz2

$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar: obj := $(abs_obj)
$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar: builddir := $(abs_builddir)
$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar: TOOLSET := $(TOOLSET)
$(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar: native_client/build/cygtar.py native_client/toolchain/.tars/toolchain_linux_x86.tar.bz2 FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain)

all_deps += $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar
action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain_outputs := $(obj)/gen/sdk/toolchain/linux_x86_glibc/stamp.untar

### Rules for action "Untar pnacl toolchain":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain = ACTION _home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain $@
cmd__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd native_client; mkdir -p $(obj)/gen/sdk/toolchain/linux_x86_pnacl; python ../native_client/build/untar_toolchain.py --tool x86_pnacl --tmp "$(obj)/gen/untar" --sdk "$(obj)/gen/sdk" --os linux ../native_client/toolchain/.tars/naclsdk_pnacl_linux_x86.tgz

$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar: obj := $(abs_obj)
$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar: builddir := $(abs_builddir)
$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar: TOOLSET := $(TOOLSET)
$(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar: native_client/build/cygtar.py native_client/toolchain/.tars/naclsdk_pnacl_linux_x86.tgz FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain)

all_deps += $(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar
action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain_outputs := $(obj)/gen/sdk/toolchain/linux_x86_pnacl/stamp.untar


### Rules for final target.
# Build our special outputs first.
$(obj).target/native_client/untar_toolchains.stamp: | $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain_outputs)

# Preserve order dependency of special output on deps.
$(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_newlib_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_x86_glibc_toolchain_outputs) $(action__home_david_Projects_spa_examples_chromium_src_native_client_tools_gyp_untar_toolchains_target_Untar_pnacl_toolchain_outputs): | 

$(obj).target/native_client/untar_toolchains.stamp: TOOLSET := $(TOOLSET)
$(obj).target/native_client/untar_toolchains.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/native_client/untar_toolchains.stamp
# Add target alias
.PHONY: untar_toolchains
untar_toolchains: $(obj).target/native_client/untar_toolchains.stamp

# Add target alias to "all" target.
.PHONY: all
all: untar_toolchains

