# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := glue
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DWEBKIT_EXTENSIONS_IMPLEMENTATION' \
	'-DWEBKIT_GLUE_IMPLEMENTATION' \
	'-DWEBKIT_PLUGINS_IMPLEMENTATION' \
	'-DGL_GLEXT_PROTOTYPES' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_ENABLE_INST_COUNT=0' \
	'-DSK_USE_POSIX_THREADS' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wno-narrowing \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wheader-hygiene \
	-Wno-unused-function \
	-Wno-char-subscripts \
	-Wno-unnamed-type-template-args \
	-Wno-c++11-extensions \
	-Wno-covered-switch-default \
	-Wstring-conversion \
	-Xclang \
	-load \
	-Xclang \
	/home/david/Projects/spa/examples/chromium/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so \
	-Xclang \
	-add-plugin \
	-Xclang \
	find-bad-constructs \
	-Xclang \
	-plugin-arg-find-bad-constructs \
	-Xclang \
	skip-virtuals-in-implementations \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/freetype2 \
	-I/usr/include/pixman-1 \
	-I/usr/include/libpng12 \
	-I/usr/include/harfbuzz \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-Wexit-time-destructors \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-Wno-narrowing \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-I$(obj).$(TOOLSET)/$(TARGET)/geni \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/ui \
	-Ithird_party/khronos \
	-Igpu \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/src/core \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Ithird_party/skia/include/pdf \
	-Ithird_party/skia/include/gpu \
	-Ithird_party/skia/include/gpu/gl \
	-Ithird_party/skia/include/pathops \
	-Ithird_party/skia/include/pipe \
	-Ithird_party/skia/include/ports \
	-Ithird_party/skia/include/utils \
	-Iskia/ext \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-I$(obj)/gen/ui/gl \
	-Ithird_party/mesa/MesaLib/include \
	-I$(obj)/gen/ui/ui_resources \
	-Iv8/include \
	-Ithird_party/WebKit/Source/Platform/chromium \
	-Ithird_party/WebKit/Source/Platform/chromium

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DWEBKIT_EXTENSIONS_IMPLEMENTATION' \
	'-DWEBKIT_GLUE_IMPLEMENTATION' \
	'-DWEBKIT_PLUGINS_IMPLEMENTATION' \
	'-DGL_GLEXT_PROTOTYPES' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_ENABLE_INST_COUNT=0' \
	'-DSK_USE_POSIX_THREADS' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DU_STATIC_IMPLEMENTATION' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wno-narrowing \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wheader-hygiene \
	-Wno-unused-function \
	-Wno-char-subscripts \
	-Wno-unnamed-type-template-args \
	-Wno-c++11-extensions \
	-Wno-covered-switch-default \
	-Wstring-conversion \
	-Xclang \
	-load \
	-Xclang \
	/home/david/Projects/spa/examples/chromium/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so \
	-Xclang \
	-add-plugin \
	-Xclang \
	find-bad-constructs \
	-Xclang \
	-plugin-arg-find-bad-constructs \
	-Xclang \
	skip-virtuals-in-implementations \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/freetype2 \
	-I/usr/include/pixman-1 \
	-I/usr/include/libpng12 \
	-I/usr/include/harfbuzz \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-Wexit-time-destructors \
	-O2 \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-Wno-narrowing \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-Ithird_party/icu/public/common \
	-Ithird_party/icu/public/i18n \
	-I$(obj).$(TOOLSET)/$(TARGET)/geni \
	-I$(obj)/gen/webkit \
	-I$(obj)/gen/ui \
	-Ithird_party/khronos \
	-Igpu \
	-I. \
	-Iskia/config \
	-Ithird_party/skia/src/core \
	-Ithird_party/skia/include/config \
	-Ithird_party/skia/include/core \
	-Ithird_party/skia/include/effects \
	-Ithird_party/skia/include/pdf \
	-Ithird_party/skia/include/gpu \
	-Ithird_party/skia/include/gpu/gl \
	-Ithird_party/skia/include/pathops \
	-Ithird_party/skia/include/pipe \
	-Ithird_party/skia/include/ports \
	-Ithird_party/skia/include/utils \
	-Iskia/ext \
	-Ithird_party/npapi \
	-Ithird_party/npapi/bindings \
	-I$(obj)/gen/ui/gl \
	-Ithird_party/mesa/MesaLib/include \
	-I$(obj)/gen/ui/ui_resources \
	-Iv8/include \
	-Ithird_party/WebKit/Source/Platform/chromium \
	-Ithird_party/WebKit/Source/Platform/chromium

OBJS := \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/gtk_plugin_container.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/gtk_plugin_container_manager.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_host.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_instance.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_lib.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_lib_posix.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_list.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_list_posix.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_stream.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_stream_posix.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_stream_url.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_string_stream.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/plugin_utils.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/webplugin.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/webplugin_delegate_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/webplugin_delegate_impl_gtk.o \
	$(obj).target/$(TARGET)/webkit/plugins/npapi/webplugin_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/plugin_constants.o \
	$(obj).target/$(TARGET)/webkit/plugins/plugin_switches.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/audio_helper.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/content_decryptor_delegate.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/event_conversion.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/file_callbacks.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/host_array_buffer_var.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/host_globals.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/host_var_tracker.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/message_channel.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/npapi_glue.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/npobject_var.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/plugin_module.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/plugin_object.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppapi_interface_factory.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppapi_plugin_instance.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppapi_webplugin_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_audio_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_broker_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_buffer_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_file_ref_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_flash_message_loop_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_gpu_blacklist_private_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_graphics_3d_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_image_data_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_network_monitor_private_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_proxy_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_scrollbar_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_tcp_server_socket_private_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_tcp_socket_private_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_uma_private_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_url_loader_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_var_deprecated_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_video_decoder_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_widget_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/ppb_x509_certificate_private_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/quota_file_io.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/resource_creation_impl.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/resource_helper.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/string.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/url_response_info_util.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/url_request_info_util.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/usb_key_code_conversion.o \
	$(obj).target/$(TARGET)/webkit/plugins/ppapi/usb_key_code_conversion_linux.o \
	$(obj).target/$(TARGET)/webkit/plugins/sad_plugin.o \
	$(obj).target/$(TARGET)/webkit/plugins/webplugininfo.o \
	$(obj).target/$(TARGET)/webkit/plugins/webview_plugin.o \
	$(obj).target/$(TARGET)/webkit/glue/alt_error_page_resource_fetcher.o \
	$(obj).target/$(TARGET)/webkit/glue/cpp_bound_class.o \
	$(obj).target/$(TARGET)/webkit/glue/cpp_variant.o \
	$(obj).target/$(TARGET)/webkit/glue/dom_operations.o \
	$(obj).target/$(TARGET)/webkit/glue/fling_curve_configuration.o \
	$(obj).target/$(TARGET)/webkit/glue/ftp_directory_listing_response_delegate.o \
	$(obj).target/$(TARGET)/webkit/glue/glue_serialize.o \
	$(obj).target/$(TARGET)/webkit/glue/image_decoder.o \
	$(obj).target/$(TARGET)/webkit/glue/image_resource_fetcher.o \
	$(obj).target/$(TARGET)/webkit/glue/multi_resolution_image_resource_fetcher.o \
	$(obj).target/$(TARGET)/webkit/glue/multipart_response_delegate.o \
	$(obj).target/$(TARGET)/webkit/glue/npruntime_util.o \
	$(obj).target/$(TARGET)/webkit/glue/resource_fetcher.o \
	$(obj).target/$(TARGET)/webkit/glue/resource_loader_bridge.o \
	$(obj).target/$(TARGET)/webkit/glue/resource_request_body.o \
	$(obj).target/$(TARGET)/webkit/glue/resource_type.o \
	$(obj).target/$(TARGET)/webkit/glue/scoped_clipboard_writer_glue.o \
	$(obj).target/$(TARGET)/webkit/glue/simple_webmimeregistry_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/touch_fling_gesture_curve.o \
	$(obj).target/$(TARGET)/webkit/glue/web_discardable_memory_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/webclipboard_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/webcookie.o \
	$(obj).target/$(TARGET)/webkit/glue/webcursor.o \
	$(obj).target/$(TARGET)/webkit/glue/webcursor_gtk.o \
	$(obj).target/$(TARGET)/webkit/glue/webdropdata.o \
	$(obj).target/$(TARGET)/webkit/glue/webfileutilities_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/webkit_glue.o \
	$(obj).target/$(TARGET)/webkit/glue/webkitplatformsupport_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/webmenuitem.o \
	$(obj).target/$(TARGET)/webkit/glue/webpreferences.o \
	$(obj).target/$(TARGET)/webkit/glue/websocketstreamhandle_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/webthemeengine_impl_default.o \
	$(obj).target/$(TARGET)/webkit/glue/webthread_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/weburlloader_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/weburlrequest_extradata_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/weburlresponse_extradata_impl.o \
	$(obj).target/$(TARGET)/webkit/glue/web_io_operators.o \
	$(obj).target/$(TARGET)/webkit/glue/worker_task_runner.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/ppapi/ppapi_c.stamp $(obj).target/third_party/npapi/npapi.stamp $(obj).target/ui/gl/libgl_wrapper.a $(obj).target/ui/ui_resources.stamp $(obj).target/v8/tools/gyp/v8.stamp $(obj).target/webkit/support/webkit_resources.stamp $(obj).target/webkit/support/webkit_strings.stamp $(obj).target/build/linux/gtk.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-L$(builddir) \
	-Wl,--icf=none

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-L$(builddir) \
	-Wl,--icf=none \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/webkit/support/libglue.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/webkit/support/libglue.a: LIBS := $(LIBS)
$(obj).target/webkit/support/libglue.a: TOOLSET := $(TOOLSET)
$(obj).target/webkit/support/libglue.a: $(OBJS) $(obj).target/ui/gl/libgl_wrapper.a FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/webkit/support/libglue.a
# Add target alias
.PHONY: glue
glue: $(obj).target/webkit/support/libglue.a

# Add target alias to "all" target.
.PHONY: all
all: glue

