./configure-llvm
make -skj8

#build stuff that normally requires `find lib | grep '\.o$'`

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o secchan/ofprotocol secchan/discovery.o secchan/emerg-flow.o secchan/fail-open.o secchan/failover.o secchan/in-band.o secchan/port-watcher.o secchan/protocol-stat.o secchan/ratelimit.o secchan/secchan.o secchan/status.o secchan/stp-secchan.o `find lib | grep '\.o'` -ldl

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o controller/controller controller/controller.o `find lib | grep '\.o$'` -ldl

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o utilities/vlogconf utilities/vlogconf.o `find lib | grep '\.o$'`

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o utilities/dpctl utilities/dpctl.o `find lib | grep '\.o$'` -ldl

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o utilities/ofp-discover utilities/ofp-discover.o `find lib | grep '\.o$'` 

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o utilities/ofp-kill utilities/ofp-kill.o `find lib | grep '\.o$'` 

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o udatapath/ofdatapath udatapath/udatapath_ofdatapath-chain.o udatapath/udatapath_ofdatapath-crc32.o udatapath/udatapath_ofdatapath-datapath.o udatapath/udatapath_ofdatapath-dp_act.o udatapath/udatapath_ofdatapath-of_ext_msg.o udatapath/udatapath_ofdatapath-udatapath.o udatapath/udatapath_ofdatapath-private-msg.o udatapath/udatapath_ofdatapath-switch-flow.o udatapath/udatapath_ofdatapath-table-hash.o udatapath/udatapath_ofdatapath-table-linear.o `find lib | grep '\.o$'`  -ldl  

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o tests/test-flows tests/test-flows.o `find lib | grep '\.o$'` 

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o tests/test-hmap tests/test-hmap.o `find lib | grep '\.o$'` 

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o tests/test-list tests/test-list.o `find lib | grep '\.o$'` 

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o tests/test-dhcp-client tests/test-dhcp-client.o `find lib | grep '\.o$'` -ldl 

llvm-gcc -Wstrict-prototypes -fomit-frame-pointer -DENABLE_SPA -DENABLE_KLEE -emit-llvm -use-gold-plugin -O0 -g -Wall -Wno-sign-compare -Wpointer-arith -Wdeclaration-after-statement -Wformat-security -Wswitch-enum -Wunused-parameter -Wstrict-aliasing -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-field-initializers -Wno-override-init   -o tests/test-stp tests/test-stp.o `find lib | grep '\.o$'` 

