# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sync
### Rules for final target.
$(obj).target/sync/sync.stamp: TOOLSET := $(TOOLSET)
$(obj).target/sync/sync.stamp: $(obj).target/sync/libsync_api.a $(obj).target/sync/libsync_core.a $(obj).target/sync/libsync_internal_api.a $(obj).target/sync/libsync_notifier.a $(obj).target/sync/libsync_proto.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/sync/sync.stamp
# Add target alias
.PHONY: sync
sync: $(obj).target/sync/sync.stamp

# Add target alias to "all" target.
.PHONY: all
all: sync

