# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sync_proto
### Generated for rule _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto:
$(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py: sync/protocol/app_notification_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_0)
$(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.h: $(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_0 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.h" --proto-in-dir protocol --proto-in-file "app_notification_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_0 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_0 $@

$(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py: sync/protocol/app_setting_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_1)
$(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.h: $(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_1 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.h" --proto-in-dir protocol --proto-in-file "app_setting_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_1 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_1 $@

$(builddir)/pyproto/sync/protocol/app_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/app_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/app_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/app_specifics_pb2.py: sync/protocol/app_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_2)
$(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.h: $(builddir)/pyproto/sync/protocol/app_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/app_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_2 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.h" --proto-in-dir protocol --proto-in-file "app_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_2 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_2 $@

$(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py: sync/protocol/autofill_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_3)
$(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.h: $(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_3 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.h" --proto-in-dir protocol --proto-in-file "autofill_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_3 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_3 $@

$(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py: sync/protocol/bookmark_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_4)
$(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.h: $(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_4 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.h" --proto-in-dir protocol --proto-in-file "bookmark_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_4 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_4 $@

$(builddir)/pyproto/sync/protocol/client_commands_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/client_commands_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/client_commands_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/client_commands_pb2.py: sync/protocol/client_commands.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_5)
$(obj)/gen/protoc_out/sync/protocol/client_commands.pb.cc $(obj)/gen/protoc_out/sync/protocol/client_commands.pb.h: $(builddir)/pyproto/sync/protocol/client_commands_pb2.py
$(obj)/gen/protoc_out/sync/protocol/client_commands.pb.cc $(obj)/gen/protoc_out/sync/protocol/client_commands.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/client_commands_pb2.py $(obj)/gen/protoc_out/sync/protocol/client_commands.pb.cc $(obj)/gen/protoc_out/sync/protocol/client_commands.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_5 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/client_commands.pb.h" --proto-in-dir protocol --proto-in-file "client_commands$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_5 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_5 $@

$(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py: sync/protocol/client_debug_info.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_6)
$(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.cc $(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.h: $(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py
$(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.cc $(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py $(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.cc $(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_6 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.h" --proto-in-dir protocol --proto-in-file "client_debug_info$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_6 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_6 $@

$(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py: sync/protocol/device_info_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_7)
$(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.h: $(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_7 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.h" --proto-in-dir protocol --proto-in-file "device_info_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_7 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_7 $@

$(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py: sync/protocol/dictionary_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_8)
$(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.h: $(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_8 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.h" --proto-in-dir protocol --proto-in-file "dictionary_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_8 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_8 $@

$(builddir)/pyproto/sync/protocol/encryption_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/encryption_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/encryption_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/encryption_pb2.py: sync/protocol/encryption.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_9)
$(obj)/gen/protoc_out/sync/protocol/encryption.pb.cc $(obj)/gen/protoc_out/sync/protocol/encryption.pb.h: $(builddir)/pyproto/sync/protocol/encryption_pb2.py
$(obj)/gen/protoc_out/sync/protocol/encryption.pb.cc $(obj)/gen/protoc_out/sync/protocol/encryption.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/encryption_pb2.py $(obj)/gen/protoc_out/sync/protocol/encryption.pb.cc $(obj)/gen/protoc_out/sync/protocol/encryption.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_9 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/encryption.pb.h" --proto-in-dir protocol --proto-in-file "encryption$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_9 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_9 $@

$(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py: sync/protocol/experiments_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_10)
$(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.h: $(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_10 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.h" --proto-in-dir protocol --proto-in-file "experiments_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_10 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_10 $@

$(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py: sync/protocol/extension_setting_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_11)
$(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.h: $(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_11 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.h" --proto-in-dir protocol --proto-in-file "extension_setting_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_11 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_11 $@

$(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py: sync/protocol/extension_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_12)
$(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.h: $(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_12 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.h" --proto-in-dir protocol --proto-in-file "extension_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_12 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_12 $@

$(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py: sync/protocol/favicon_image_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_13)
$(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.h: $(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_13 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.h" --proto-in-dir protocol --proto-in-file "favicon_image_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_13 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_13 $@

$(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py: sync/protocol/favicon_tracking_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_14)
$(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.h: $(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_14 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.h" --proto-in-dir protocol --proto-in-file "favicon_tracking_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_14 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_14 $@

$(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py: sync/protocol/get_updates_caller_info.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_15)
$(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.cc $(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.h: $(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py
$(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.cc $(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py $(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.cc $(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_15 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.h" --proto-in-dir protocol --proto-in-file "get_updates_caller_info$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_15 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_15 $@

$(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py: sync/protocol/history_delete_directive_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_16)
$(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.h: $(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_16 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.h" --proto-in-dir protocol --proto-in-file "history_delete_directive_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_16 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_16 $@

$(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py: sync/protocol/nigori_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_17)
$(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.h: $(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_17 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.h" --proto-in-dir protocol --proto-in-file "nigori_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_17 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_17 $@

$(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py: sync/protocol/managed_user_setting_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_18)
$(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.h: $(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_18 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.h" --proto-in-dir protocol --proto-in-file "managed_user_setting_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_18 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_18 $@

$(builddir)/pyproto/sync/protocol/password_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/password_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/password_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/password_specifics_pb2.py: sync/protocol/password_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_19)
$(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.h: $(builddir)/pyproto/sync/protocol/password_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/password_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_19 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.h" --proto-in-dir protocol --proto-in-file "password_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_19 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_19 $@

$(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py: sync/protocol/preference_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_20)
$(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.h: $(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_20 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.h" --proto-in-dir protocol --proto-in-file "preference_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_20 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_20 $@

$(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py: sync/protocol/priority_preference_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_21)
$(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.h: $(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_21 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.h" --proto-in-dir protocol --proto-in-file "priority_preference_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_21 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_21 $@

$(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py: sync/protocol/search_engine_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_22)
$(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.h: $(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_22 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.h" --proto-in-dir protocol --proto-in-file "search_engine_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_22 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_22 $@

$(builddir)/pyproto/sync/protocol/session_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/session_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/session_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/session_specifics_pb2.py: sync/protocol/session_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_23)
$(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.h: $(builddir)/pyproto/sync/protocol/session_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/session_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_23 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.h" --proto-in-dir protocol --proto-in-file "session_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_23 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_23 $@

$(builddir)/pyproto/sync/protocol/sync_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/sync_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/sync_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/sync_pb2.py: sync/protocol/sync.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_24)
$(obj)/gen/protoc_out/sync/protocol/sync.pb.cc $(obj)/gen/protoc_out/sync/protocol/sync.pb.h: $(builddir)/pyproto/sync/protocol/sync_pb2.py
$(obj)/gen/protoc_out/sync/protocol/sync.pb.cc $(obj)/gen/protoc_out/sync/protocol/sync.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/sync_pb2.py $(obj)/gen/protoc_out/sync/protocol/sync.pb.cc $(obj)/gen/protoc_out/sync/protocol/sync.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_24 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/sync.pb.h" --proto-in-dir protocol --proto-in-file "sync$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_24 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_24 $@

$(builddir)/pyproto/sync/protocol/sync_enums_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/sync_enums_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/sync_enums_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/sync_enums_pb2.py: sync/protocol/sync_enums.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_25)
$(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.cc $(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.h: $(builddir)/pyproto/sync/protocol/sync_enums_pb2.py
$(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.cc $(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/sync_enums_pb2.py $(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.cc $(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_25 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.h" --proto-in-dir protocol --proto-in-file "sync_enums$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_25 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_25 $@

$(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py: sync/protocol/synced_notification_data.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_26)
$(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.h: $(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py
$(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py $(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_26 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.h" --proto-in-dir protocol --proto-in-file "synced_notification_data$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_26 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_26 $@

$(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py: sync/protocol/synced_notification_render.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_27)
$(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.h: $(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py
$(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py $(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_27 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.h" --proto-in-dir protocol --proto-in-file "synced_notification_render$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_27 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_27 $@

$(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py: sync/protocol/synced_notification_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_28)
$(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.h: $(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_28 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.h" --proto-in-dir protocol --proto-in-file "synced_notification_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_28 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_28 $@

$(builddir)/pyproto/sync/protocol/test_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/test_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/test_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/test_pb2.py: sync/protocol/test.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_29)
$(obj)/gen/protoc_out/sync/protocol/test.pb.cc $(obj)/gen/protoc_out/sync/protocol/test.pb.h: $(builddir)/pyproto/sync/protocol/test_pb2.py
$(obj)/gen/protoc_out/sync/protocol/test.pb.cc $(obj)/gen/protoc_out/sync/protocol/test.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/test_pb2.py $(obj)/gen/protoc_out/sync/protocol/test.pb.cc $(obj)/gen/protoc_out/sync/protocol/test.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_29 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/test.pb.h" --proto-in-dir protocol --proto-in-file "test$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_29 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_29 $@

$(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py: sync/protocol/theme_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_30)
$(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.h: $(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_30 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.h" --proto-in-dir protocol --proto-in-file "theme_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_30 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_30 $@

$(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py: sync/protocol/typed_url_specifics.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_31)
$(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.h: $(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py
$(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py $(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.cc $(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_31 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.h" --proto-in-dir protocol --proto-in-file "typed_url_specifics$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_31 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_31 $@

$(builddir)/pyproto/sync/protocol/unique_position_pb2.py: obj := $(abs_obj)
$(builddir)/pyproto/sync/protocol/unique_position_pb2.py: builddir := $(abs_builddir)
$(builddir)/pyproto/sync/protocol/unique_position_pb2.py: TOOLSET := $(TOOLSET)
$(builddir)/pyproto/sync/protocol/unique_position_pb2.py: sync/protocol/unique_position.proto tools/protoc_wrapper/protoc_wrapper.py $(builddir)/protoc FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_32)
$(obj)/gen/protoc_out/sync/protocol/unique_position.pb.cc $(obj)/gen/protoc_out/sync/protocol/unique_position.pb.h: $(builddir)/pyproto/sync/protocol/unique_position_pb2.py
$(obj)/gen/protoc_out/sync/protocol/unique_position.pb.cc $(obj)/gen/protoc_out/sync/protocol/unique_position.pb.h: ;

all_deps += $(builddir)/pyproto/sync/protocol/unique_position_pb2.py $(obj)/gen/protoc_out/sync/protocol/unique_position.pb.cc $(obj)/gen/protoc_out/sync/protocol/unique_position.pb.h
cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_32 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd sync; mkdir -p $(builddir)/pyproto/sync/protocol $(obj)/gen/protoc_out/sync/protocol; python ../tools/protoc_wrapper/protoc_wrapper.py --include sync/base/sync_export.h --protobuf "$(obj)/gen/protoc_out/sync/protocol/unique_position.pb.h" --proto-in-dir protocol --proto-in-file "unique_position$(suffix $<)" "--use-system-protobuf=0" -- "$(builddir)/protoc" --cpp_out "dllexport_decl=SYNC_EXPORT:$(obj)/gen/protoc_out/sync/protocol" --python_out "$(builddir)/pyproto/sync/protocol"
quiet_cmd__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_32 = RULE _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_32 $@

rule__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_outputs := \
	$(builddir)/pyproto/sync/protocol/app_notification_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/app_setting_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/app_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/app_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/autofill_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/autofill_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/bookmark_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/client_commands_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/client_commands.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/client_commands.pb.h \
	$(builddir)/pyproto/sync/protocol/client_debug_info_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/client_debug_info.pb.h \
	$(builddir)/pyproto/sync/protocol/device_info_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/device_info_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/dictionary_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/encryption_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/encryption.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/encryption.pb.h \
	$(builddir)/pyproto/sync/protocol/experiments_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/experiments_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/extension_setting_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/extension_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/extension_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/favicon_image_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/favicon_tracking_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/get_updates_caller_info_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.h \
	$(builddir)/pyproto/sync/protocol/history_delete_directive_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/nigori_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/nigori_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/managed_user_setting_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/password_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/password_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/preference_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/preference_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/priority_preference_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/search_engine_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/session_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/session_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/sync_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/sync.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/sync.pb.h \
	$(builddir)/pyproto/sync/protocol/sync_enums_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/sync_enums.pb.h \
	$(builddir)/pyproto/sync/protocol/synced_notification_data_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/synced_notification_data.pb.h \
	$(builddir)/pyproto/sync/protocol/synced_notification_render_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/synced_notification_render.pb.h \
	$(builddir)/pyproto/sync/protocol/synced_notification_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/test_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/test.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/test.pb.h \
	$(builddir)/pyproto/sync/protocol/theme_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/theme_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/typed_url_specifics_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.h \
	$(builddir)/pyproto/sync/protocol/unique_position_pb2.py \
	$(obj)/gen/protoc_out/sync/protocol/unique_position.pb.cc \
	$(obj)/gen/protoc_out/sync/protocol/unique_position.pb.h

### Finished generating for rule: _home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto

### Finished generating for all rules

DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DSYNC_IMPLEMENTATION' \
	'-DPROTOBUF_USE_DLLS' \
	'-DGOOGLE_PROTOBUF_NO_RTTI' \
	'-DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-I. \
	-I$(obj)/gen/protoc_out \
	-Ithird_party/protobuf \
	-Ithird_party/protobuf/src

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DSYNC_IMPLEMENTATION' \
	'-DPROTOBUF_USE_DLLS' \
	'-DGOOGLE_PROTOBUF_NO_RTTI' \
	'-DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-I. \
	-I$(obj)/gen/protoc_out \
	-Ithird_party/protobuf \
	-Ithird_party/protobuf/src

OBJS := \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/app_notification_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/app_setting_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/app_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/autofill_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/bookmark_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/client_commands.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/client_debug_info.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/device_info_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/dictionary_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/encryption.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/experiments_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/extension_setting_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/extension_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/favicon_image_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/favicon_tracking_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/get_updates_caller_info.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/history_delete_directive_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/nigori_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/managed_user_setting_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/password_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/preference_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/priority_preference_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/search_engine_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/session_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/sync.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/sync_enums.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/synced_notification_data.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/synced_notification_render.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/synced_notification_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/test.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/theme_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/typed_url_specifics.pb.o \
	$(obj).target/$(TARGET)/gen/protoc_out/sync/protocol/unique_position.pb.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(builddir)/protoc

# Make sure our actions/rules run before any of us.
$(OBJS): | $(rule__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/sync/libsync_proto.a: | $(rule__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_outputs)

# Preserve order dependency of special output on deps.
$(rule__home_david_Projects_spa_examples_chromium_src_sync_sync_gyp_sync_proto_target_genproto_outputs): | $(builddir)/protoc

LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-Wl,--icf=none

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,--threads \
	-Wl,--thread-count=4 \
	-B$(builddir)/../../third_party/gold \
	-Wl,--icf=none \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/sync/libsync_proto.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/sync/libsync_proto.a: LIBS := $(LIBS)
$(obj).target/sync/libsync_proto.a: TOOLSET := $(TOOLSET)
$(obj).target/sync/libsync_proto.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/sync/libsync_proto.a
# Add target alias
.PHONY: sync_proto
sync_proto: $(obj).target/sync/libsync_proto.a

# Add target alias to "all" target.
.PHONY: all
all: sync_proto

