# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := test_shell_pak
### Rules for action "test_shell_repack":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack = ACTION _home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack $@
cmd__home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd webkit; mkdir -p $(obj).$(TOOLSET)/test_shell_pak/geni/repack; python ../tools/grit/grit/format/repack.py "$(obj).$(TOOLSET)/test_shell_pak/geni/repack/test_shell.pak" "$(obj)/gen/net/net_resources.pak" "$(obj)/gen/test_shell/test_shell_resources.pak" "$(obj)/gen/ui/ui_resources/ui_resources_100_percent.pak" "$(obj)/gen/webkit/webkit_chromium_resources.pak" "$(obj)/gen/webkit/webkit_resources_100_percent.pak" "$(obj)/gen/webkit/webkit_strings_en-US.pak"

$(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak: obj := $(abs_obj)
$(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak: builddir := $(abs_builddir)
$(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak: TOOLSET := $(TOOLSET)
$(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak: tools/grit/grit/format/repack.py $(obj)/gen/net/net_resources.pak $(obj)/gen/test_shell/test_shell_resources.pak $(obj)/gen/ui/ui_resources/ui_resources_100_percent.pak $(obj)/gen/webkit/webkit_chromium_resources.pak $(obj)/gen/webkit/webkit_resources_100_percent.pak $(obj)/gen/webkit/webkit_strings_en-US.pak FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack)

all_deps += $(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak
action__home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack_outputs := $(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak


### Generated for copy rule.
$(builddir)/test_shell.pak: TOOLSET := $(TOOLSET)
$(builddir)/test_shell.pak: $(obj).$(TOOLSET)/$(TARGET)/geni/repack/test_shell.pak FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/test_shell.pak
_home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_copies = $(builddir)/test_shell.pak

### Rules for final target.
# Build our special outputs first.
$(obj).target/webkit/test_shell_pak.stamp: | $(action__home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack_outputs) $(_home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_copies)

# Preserve order dependency of special output on deps.
$(action__home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_test_shell_repack_outputs) $(_home_david_Projects_spa_examples_chromium_src_webkit_webkit_gyp_test_shell_pak_target_copies): | 

$(obj).target/webkit/test_shell_pak.stamp: TOOLSET := $(TOOLSET)
$(obj).target/webkit/test_shell_pak.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/webkit/test_shell_pak.stamp
# Add target alias
.PHONY: test_shell_pak
test_shell_pak: $(obj).target/webkit/test_shell_pak.stamp

# Add target alias to "all" target.
.PHONY: all
all: test_shell_pak

