# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := content_shell_builder
### Rules for final target.
$(obj).target/content/content_shell_builder.stamp: TOOLSET := $(TOOLSET)
$(obj).target/content/content_shell_builder.stamp: $(builddir)/content_shell FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/content/content_shell_builder.stamp
# Add target alias
.PHONY: content_shell_builder
content_shell_builder: $(obj).target/content/content_shell_builder.stamp

# Add target alias to "all" target.
.PHONY: all
all: content_shell_builder

