# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := autofill_regexes
### Rules for action "autofill_regexes":
quiet_cmd__home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes = ACTION _home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes $@
cmd__home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd components; mkdir -p $(obj)/gen; python ../build/escape_unicode.py -o "$(obj)/gen" autofill/browser/autofill_regex_constants.cc.utf8

$(obj)/gen/autofill_regex_constants.cc: obj := $(abs_obj)
$(obj)/gen/autofill_regex_constants.cc: builddir := $(abs_builddir)
$(obj)/gen/autofill_regex_constants.cc: TOOLSET := $(TOOLSET)
$(obj)/gen/autofill_regex_constants.cc: build/escape_unicode.py components/autofill/browser/autofill_regex_constants.cc.utf8 FORCE_DO_CMD
	$(call do_cmd,_home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes)

all_deps += $(obj)/gen/autofill_regex_constants.cc
action__home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes_outputs := $(obj)/gen/autofill_regex_constants.cc


### Rules for final target.
# Build our special outputs first.
$(obj).target/components/autofill_regexes.stamp: | $(action__home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes_outputs)

# Preserve order dependency of special output on deps.
$(action__home_david_Projects_spa_examples_chromium_src_components_components_gyp_autofill_regexes_target_autofill_regexes_outputs): | 

$(obj).target/components/autofill_regexes.stamp: TOOLSET := $(TOOLSET)
$(obj).target/components/autofill_regexes.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/components/autofill_regexes.stamp
# Add target alias
.PHONY: autofill_regexes
autofill_regexes: $(obj).target/components/autofill_regexes.stamp

# Add target alias to "all" target.
.PHONY: all
all: autofill_regexes

